# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, df, fid, review_df):
        self.df = df.loc[df['place'] == int(fid)]
        self.fid = fid
        self.review_df = review_df.loc[review_df['film_id'] == int(fid)]

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(656, 582)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 131, 193, 255), stop:1 rgba(75, 196, 113, 255));")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 641, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 230, 651, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(550, 10, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(66, 201, 35, 255), stop:0.886364 rgba(255, 255, 255, 0));")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")


        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 278, 652, 300))
        self.scrollArea.setMaximumSize(QtCore.QSize(700, 300))
        self.scrollArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollArea.setAcceptDrops(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget = QtWidgets.QWidget()
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 718, 433))
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.widget_review = []
        self.label_name = []
        self.label_score = []
        self.label_sumary = []
        self.line_review = []
        index = 0
        for i, row in self.review_df.iterrows():
            self.widget_review.append(QtWidgets.QWidget(self.widget))
            self.widget_review[index].setMinimumSize(QtCore.QSize(700, 200))
            self.widget_review[index].setMaximumSize(QtCore.QSize(636, 700))
            self.widget_review[index].setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 131, 193, 255), stop:1 rgba(75, 196, 113, 255));")
            self.label_name.append(QtWidgets.QLabel(self.widget_review[index]))
            self.label_name[index].setGeometry(QtCore.QRect(0, 0, 700, 49))
            font = QtGui.QFont()
            font.setFamily("Segoe UI Historic")
            font.setPointSize(16)
            self.label_name[index].setFont(font)
            self.label_score.append(QtWidgets.QLabel(self.widget_review[index]))
            self.label_score[index].setGeometry(QtCore.QRect(540, 1, 80, 80))
            font = QtGui.QFont()
            font.setFamily("Segoe UI Historic")
            font.setPointSize(28)
            self.label_score[index].setFont(font)
            if row['score'] > 60:
                self.label_score[index].setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(140, 222, 52, 1), stop:0.886364 rgba(255, 255, 255, 0));")
            elif row['score'] > 40:
                self.label_score[index].setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(245, 204, 58, 1), stop:0.886364 rgba(255, 255, 255, 0));")
            else:
                self.label_score[index].setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(245, 63, 58, 1), stop:0.886364 rgba(255, 255, 255, 0));")
            
            self.label_score[index].setAlignment(QtCore.Qt.AlignCenter)
            font = QtGui.QFont()
            font.setFamily("Segoe UI Historic")
            font.setPointSize(12)
            self.label_sumary.append(QtWidgets.QLabel(self.widget_review[index]))
            self.label_sumary[index].setGeometry(QtCore.QRect(0, 70, 621, 131))
            self.label_sumary[index].setMaximumSize(QtCore.QSize(700, 300))
            self.label_sumary[index].setFont(font)
            self.label_sumary[index].setMouseTracking(False)
            self.label_sumary[index].setAutoFillBackground(False)
            self.label_sumary[index].setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
            self.label_sumary[index].setFrameShadow(QtWidgets.QFrame.Plain)
            self.label_sumary[index].setScaledContents(False)
            self.label_sumary[index].setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
            self.label_sumary[index].setWordWrap(True)
            self.label_sumary[index].raise_()
            self.label_name[index].raise_()
            self.label_score[index].raise_()
            self.verticalLayout.addWidget(self.widget_review[index])
            self.line_review.append(QtWidgets.QFrame(self.widget))
            self.line_review[index].setFrameShape(QtWidgets.QFrame.HLine)
            self.line_review[index].setFrameShadow(QtWidgets.QFrame.Sunken)
            self.verticalLayout.addWidget(self.line_review[index])
            index += 1
        self.scrollArea.setWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        title = self.df['title'].iloc[0]
        date = self.df['date'].iloc[0]
        score = self.df['metascore'].iloc[0]
        sumary = self.df['sumary'].iloc[0]
        rating = self.df['rating'].iloc[0]
        url = self.df['url'].iloc[0]
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", f"{title}"))
        if score > 60:
            self.label_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(140, 222, 52, 1), stop:0.886364 rgba(255, 255, 255, 0));")
        elif score > 40:
            self.label_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(245, 204, 58, 1), stop:0.886364 rgba(255, 255, 255, 0));")
        else:
            self.label_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.880682 rgba(245, 63, 58, 1), stop:0.886364 rgba(255, 255, 255, 0));")
        self.label.setOpenExternalLinks(True)
        self.label.setText(_translate("Form", f"<a  style='color: rgb(0,0,0); text-decoration: none;' href='https://www.metacritic.com{url}'>{title}</a>"))
        self.label_2.setText(_translate("Form", f"{sumary}"))
        self.label_3.setText(_translate("Form", f"{date} | {rating}"))
        self.label_4.setText(_translate("Form", f"{score}"))
        index = 0
        for i, row in self.review_df.iterrows():
                self.label_name[index].setText(_translate("Form", f"{row['critic']}"))
                self.label_score[index].setText(_translate("Form", f"{row['score']}"))
                self.label_sumary[index].setText(_translate("Form", f"{row['review']}"))
                index += 1

        
        

