# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tensorflow import keras
from tensorflow.keras.preprocessing.sequence import pad_sequences
import pickle
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        self.model_cnn = keras.models.load_model('best_model_cnn.h5')
        self.model_lstm = keras.models.load_model('best_model_lstm.h5')
        self.model_gru = keras.models.load_model('best_model_gru.h5')
        with open('tokenizer.pickle', 'rb') as handle:
            self.tokenizer = pickle.load(handle)
        self.max_len = 180
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(579, 403)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 131, 193, 255), stop:1 rgba(75, 196, 113, 255));")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(40, 60, 290, 270))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 340, 290, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(340, 60, 221, 311))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(40, 20, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        self.pushButton.clicked.connect(self.predict)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Historic\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Predict"))
        self.label.setText(_translate("Form", ""))
        self.comboBox.setItemText(0, _translate("Form", "Convolutional neural network"))
        self.comboBox.setItemText(1, _translate("Form", "Long short-term memory"))
        self.comboBox.setItemText(2, _translate("Form", "Gated recurrent unit"))

    def predict(self):
        text = self.textEdit.toPlainText()
        choise = self.comboBox.currentText()
        if choise == 'Convolutional neural network':
            model = self.model_cnn
        elif choise == 'Long short-term memory':
            model = self.model_lstm
        elif choise == 'Gated recurrent unit':
            model = self.model_gru
        text = self.tokenizer.texts_to_sequences([text])
        text = pad_sequences(text, maxlen=self.max_len)
        prediction = model.predict(text)
        p = round(prediction[0][0]*100, 2)
        m = round(prediction[0][1]*100, 2)
        n = round(prediction[0][2]*100, 2)
        self.label.setText(f"Chances:\nPositive: {p}%\nMixed: {m}%\nNegative: {n}%")
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
